import Head from 'next/head';
import Link from 'next/link';
import styles from 'styles/Home.module.scss';
import { DashboardLayout } from 'layouts/DashboardLayout';
import { AppPage } from 'types/app.types';
import { useContext } from 'react';
import { notificationContext } from '@/contextProviders/notifications/notification.context';
import { ThemeContext } from '@/contextProviders/themes/theme.context';
import { func } from 'prop-types';

const Home: AppPage = () => {
  const { notifications } = useContext(notificationContext);
  const { switchTheme } = useContext(ThemeContext);
  function applyNewTheme() {
    switchTheme({
      colors: {
        primary: 'blue',
      },
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <table>
        <tbody>
          {notifications.map((n) => {
            return (
              <tr key={n}>
                <td>{n}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/about">Next.js!</Link>
        </h1>

        <button className="bg-primary" onClick={applyNewTheme}>
          Switch Theme
        </button>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid + ' bg-primary'}>
          <a href="https://nextjs.org/docs" className={styles.card + ' !hover:text-green-500'}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <div>
            {' '}
            <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </div>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>
    </div>
  );
};

Home.layout = DashboardLayout;
export default Home;
